### ISSUE TITLE
/modpacktools inv does not include hotbar

### ISSUE THREAD

**Issue by Goldenlion5648** [Dutchs/ModpackTools#1]
It is true that the /modpacktools hot command exists, but I think the default /modpacktools inv command should include the hotbar. If the current behavior is desired still, maybe another command could be added or a flag for the current command?

**Comment by Goldenlion5648** [comment]
https://github.com/Dutchs/ModpackTools/blob/6d7fec34bf730b33660980a44d5b1f38b02a30ba/src/main/java/com/dutchs/modpacktools/network/InventoryPacket.java#L65 The 9 here just has to be changed to a 0

**Comment by Dutchs** [comment]
sure, i'm not apposed to making that change.
